# .devcontainer/docker-compose.yml
version: "3.9"
services:
  latte-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      # Apple Silicon でも “linux/amd64” を強制すれば x86 ビルド確認も可能
      # platform: linux/amd64
    volumes:
      - ..:/workspace:cached
    tty: true
    # 必要なら GPU を有効化 (Linux/NVIDIA Docker)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
