services:
  latte-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      # Apple Silicon でも "linux/amd64" を強制ビルドしたい場合は↓を解除
      # platform: linux/amd64
    volumes:
      - ..:/workspace:cached
    tty: true
